### SVD (Singular Value Decomposition)

- Matrix Decomposition
- Data Reduction
- Data driven generalization of FFT
- Linear system of eqs **Ax=B** for non square A matrix
- Basis for PCA
- Correlation

**Uses:**
- Page Rank Algorithm
- Facial Recognition
- Recommender Systems


![Alt Text](Linear_Algebra.jpeg)
![Alt Text](Linear_Algebra2.jpeg)
![Alt Text](Linear_Algebra3.jpeg)
![Alt Text](Linear_Algebra4.jpeg)
![Alt Text](Linear_Algebra5.jpeg)

In [1]:
import numpy as np

In [2]:
X = np.random.rand(5, 3)
U, S, V = np.linalg.svd(X, full_matrices=True)
Uhat, Shat, Vhat = np.linalg.svd(X, full_matrices=False)  # economy SVD

In [5]:
print(U)
print(S)
print(V)

[[-0.51776933 -0.16644234 -0.44090059 -0.69560586 -0.16109322]
 [-0.21025912  0.8366123  -0.44788707  0.22291652  0.07467508]
 [-0.35252387 -0.5081222  -0.44335814  0.62313492  0.18076281]
 [-0.7305582   0.11545762  0.61145755  0.17884858 -0.21699563]
 [-0.17238812  0.02929474  0.18589532 -0.21484128  0.94271433]]
[1.90969205 0.71613383 0.31031824]
[[-0.32190766 -0.54494291 -0.77421747]
 [ 0.71249281  0.39907834 -0.57713991]
 [-0.62348172  0.73741013 -0.25980153]]


In [6]:
print(Uhat)
print(Shat)
print(Vhat)


[[-0.51776933 -0.16644234 -0.44090059]
 [-0.21025912  0.8366123  -0.44788707]
 [-0.35252387 -0.5081222  -0.44335814]
 [-0.7305582   0.11545762  0.61145755]
 [-0.17238812  0.02929474  0.18589532]]
[1.90969205 0.71613383 0.31031824]
[[-0.32190766 -0.54494291 -0.77421747]
 [ 0.71249281  0.39907834 -0.57713991]
 [-0.62348172  0.73741013 -0.25980153]]
